name: CI-CD

on:
  workflow_dispatch:
  push:
    branches:
      - master # master environment
      # - release # staging and production 


jobs:
  build-core-api:
    uses: johndcna/reusable-workflows/.github/workflows/build-dotnet.yml@main
    with:
      dotnet_version: 8.x
      artifact_name: 'Cenamon.WebAPI'
      project_file: 'Cenamon/Cenamon.WebAPI.csproj'
      path: 'Cenamon/artifact/content'
      
  deploy-core-api:
    needs: [build-core-api]
    uses: johndcna/reusable-workflows/.github/workflows/deploy-.net-to-azure-web-app.yml@main
    with:
      artifact_name: 'Cenamon.WebAPI'
      target_app_name: ${{ vars.APP_NAME }}
      target_publish_profile: ${{ vars.PUBLISHED_PROFILE }}
    secrets:
      azure_client_id: ${{ secrets.CLIENT_ID }}
      azure_tenant_id: ${{ secrets.TENANT_ID }}
      subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      
