name: Dev

on:
  workflow_dispatch:
jobs:
  test-reusable:
    uses: johndcna/reusable-workflows/.github/workflows/test.yml@main
    with:
      fname:  ${{vars.AZURE_WEBAPP_NAME}}
      path: 'Cenamon/artifact/content'
      
