name: Dev

on:
  workflow_dispatch:
  push:
    branches:
      - master # master environment
      # - release # staging and production 


jobs:
  test-variable:
    runs-on: ubuntu-latest
    steps:        
    - name: Echo AZURE_WEBAPP_NAME
      run: |
            echo "This is a secret: ${{ env.AZURE_WEBAPP_NAME }}"
  
  test-reusable:
    uses: johndcna/reusable-workflows/.github/workflows/test.yml@main
    with:
      fname: 'testf'
      path: 'Cenamon/artifact/content'
      
